### ISSUE TITLE
支持 sonar 或fireline 静态代码扫描的集成吗

### ISSUE THREAD

**Issue by merhuge** [FlowCI/flow-core-x#326]

**Comment by gy2006** [comment]
目前还没有相关的插件，不过可以通过自定义脚本来实现相关功能

比如 fireline

```yaml
steps:
  - name: clone
    plugin: 'gitclone'
    allow_failure: false

  - name: fireline
    docker:
        image: openjdk:8
    script: |
        wget http://magic.360.cn/fireline_1.7.3.jar
        java -jar fireline_1.7.3 -s=./xx -r=./xx
```
