### ISSUE TITLE
k8s dynamic agents异常

### ISSUE THREAD

**Issue by bnubobby** [FlowCI/flow-core-x#378]
在创建　k8s　 dynamic agents　后，运行任务，出现异常：

/bin/bash: line 11: python3: command not found

**Comment by gy2006** [comment]
可以看以下 YAML 配置嘛？
目前 Agent 镜像没有安装 python3 ，而有些插件需要 python3 的运行环境.

可以在 step 中指定一个 docker 的运行环境，这样会自动加载 python
```yaml
steps:
  - name: test
    docker:
      image: "ubuntu:18.04"
    script: |
      python3 -V
```
