### ISSUE TITLE
如何用自己的私有仓库镜像

### ISSUE THREAD

**Issue by hellocloudnative** [FlowCI/flow-core-x#382]
当我用镜像为自己的私有仓库镜像时

提示报错信息，需要输入docker login

![image](https://user-images.githubusercontent.com/32674956/101148463-9cc35100-3658-11eb-8745-dd83c4de4874.png)

**Comment by gy2006** [comment]
这个功能本来计划在下下个版本支持的，既然提了现在就加上了 😄 

Pull 下最新的镜像

```bash
docker pull flowci/core
docker pull flowci/agent
```

YAML 配置如下

```yaml
docker:
  image: your_image_from_private_docker_registry
  auth: secret_name
```
secret_name 是密钥名称，在 设置 -> 密钥管理 -> 新建，选择 Category 为 Auth pair, 之后输入 docker 的用户名和密码

![](https://trello-attachments.s3.amazonaws.com/58205a83d243c35dfde30943/5fcb8a9b288a06425d0cb5d7/cf98a6218dffdd4064e1ea9ad416fc27/Screenshot_2020-12-05_at_23.52.16.png)
