### ISSUE TITLE
java.lang.Exception: No such property: FLOWCI_GIT_BRANCH for class: Script1

### ISSUE THREAD

**Issue by genkin-he** [FlowCI/flow-core-x#392]
我想只是master分支才触发构建，写了个condition运行的时候报错了，不知道我的用法是不是有问题。
> java.lang.Exception: No such property: FLOWCI_GIT_BRANCH for class: Script1

```
- name: build
    envs:
    condition: |
      return "${FLOWCI_GIT_BRANCH}" == "master"
```

![image](https://user-images.githubusercontent.com/7637282/109997772-81490e80-7d4b-11eb-9f38-a146f30540ab.png)
