### ISSUE TITLE
Question: How to add condition to entire flow

### ISSUE THREAD

**Issue by luke-riu** [FlowCI/flow-core-x#397]
For example.
I have a web hook for push requests in GitHub to call `https://<url>/webhooks/deploy` but I only want the flow to run if the branch name in git is called "deployment". Is there a way to put a condition on the entire flow to only run if it meets a certain condition? 
I see there is a 
```yaml
condition: |
  return ${branch name}
```

but that looks like it's only on individual steps.
Thanks

**Comment by luke-riu** [comment]
It turns out this works with real web hooks but not when a flow is run manually.

example:
```yaml
envs:


condition: |
  return FLOWCI_GIT_BRANCH == "distribute"

steps:
```
